# Generated by Django 2.2.7 on 2019-11-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('student_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('graduate', models.BooleanField()),
            ],
        ),
    ]
